'use client';
import {useEffect,useState} from 'react';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import initial from '@/data/fundamentals.json';
import {coreFactors,fundamentalScore,type FundamentalData} from '@/lib/fundamentals';
const fmt=(n:number|null)=>n===null?'—':n>0?'+'+n:String(n);
const date=(s:string,time=true)=>new Date(s).toLocaleString('cs-CZ',{timeZone:'Europe/Prague',day:'numeric',month:'short',year:'numeric',...(time?{hour:'2-digit',minute:'2-digit'} as const:{})});
export default function FundamentalAnalyzer(){
 const [data,setData]=useState(initial as FundamentalData),[instrument,setInstrument]=useState('EUR/USD'),[tab,setTab]=useState('report'),[now,setNow]=useState(Date.now()),[error,setError]=useState(''),[detail,setDetail]=useState(false),[query,setQuery]=useState('');
 useEffect(()=>{const refresh=async()=>{try{const r=await fetch('/api/fundamentals',{cache:'no-store'});if(!r.ok)throw Error();setData(await r.json());setError('')}catch{setError('Aktualizaci se nepodařilo načíst. Zobrazuji poslední dostupný report.')}};refresh();const t=setInterval(refresh,300000),clock=setInterval(()=>setNow(Date.now()),60000);return()=>{clearInterval(t);clearInterval(clock)}},[]);
 const currencies=Object.keys(data.currencies),result=fundamentalScore(data,instrument,now),selected=result.quote?[result.base,result.quote]:[result.base];
 const openDetail=(pair:string)=>{setInstrument(pair);setDetail(true);setTab('report');window.scrollTo({top:0,behavior:'smooth'})};
 const source=(id:string)=>data.sources[id]?<a href={data.sources[id].url} target="_blank" rel="noreferrer" className="text-link">{data.sources[id].label} ↗</a>:null;
 if(!detail)return <div className="fundamental"><div className="heading"><div><div className="eyebrow">PŘEHLED TRHU</div><h1>Páry a skóre<span>.</span></h1><p>Vyber pár a otevři report, ukazatele a makro kalendář.</p></div><input aria-label="Vyhledat pár" placeholder="Hledat pár, např. EUR" value={query} onChange={e=>setQuery(e.target.value)}/></div><p className="f-status">Ověřeno {date(data.checkedAt)} · Skóre čtyř pilířů · 11 sledovaných ukazatelů v detailu</p>{error&&<p className="connection-note">{error}</p>}<section className="panel"><Table><TableHeader><TableRow><TableHead>Pár / index</TableHead><TableHead>Skóre</TableHead><TableHead>Výhled</TableHead><TableHead>Podklady</TableHead></TableRow></TableHeader><TableBody>{[...['EUR/USD','AUD/USD','NZD/USD','USD/CAD','USD/JPY','EUR/AUD','EUR/NZD','EUR/CAD','EUR/JPY','AUD/NZD','AUD/CAD','AUD/JPY','NZD/CAD','NZD/JPY','CAD/JPY'],...currencies].filter(p=>p.includes(query.trim().toUpperCase().replace(/\s/g,''))).map(p=>{const r=fundamentalScore(data,p,now);return <TableRow key={p} className="pair-row" onClick={()=>openDetail(p)}><TableCell><button className="text-link" onClick={e=>{e.stopPropagation();openDetail(p)}}>{p}{p.includes('/')?'':' · index'} ↗</button></TableCell><TableCell><b className={r.score!==null&&r.score<0?'negative':'positive'}>{fmt(r.score)}</b></TableCell><TableCell>{r.bias}</TableCell><TableCell>{r.stale?'Čeká na nové ověření':r.available+'/4 pilíře'}</TableCell></TableRow>})}</TableBody></Table></section><p className="small-note">Zobrazeno 15 jedinečných párů a 6 vlastních indexů. Obrácený pár lze vybrat v detailu. Skóre není součtem všech 11 ukazatelů.</p></div>;
 return <div className="fundamental"><button className="text-link" onClick={()=>setDetail(false)}>← Všechny páry a skóre</button><div className="heading"><div><div className="eyebrow">VEŘEJNÉ ZDROJE · VLASTNÍ METODIKA</div><h1>Fundament v souvislostech<span>.</span></h1><p>Měnová politika, ekonomika a události, které mohou změnit směr.</p></div><select aria-label="Měna nebo pár" value={instrument} onChange={e=>setInstrument(e.target.value)}><optgroup label="Měnové páry">{currencies.flatMap(a=>currencies.filter(b=>a!==b).map(b=><option key={a+b}>{a}/{b}</option>))}</optgroup><optgroup label="Vlastní měnové indexy">{currencies.map(c=><option key={c} value={c}>{c} index</option>)}</optgroup></select></div>
 <div className="f-status"><span>Ověřeno {date(data.checkedAt)} · Praha</span><span>Plán kontrol: každé {data.reviewCadenceHours} hodiny</span><span>{result.stale?'Data čekají na nové ověření':data.horizon}</span></div>{error&&<p className="connection-note">{error}</p>}
 <div className="f-overview"><section className="panel f-score"><div className="eyebrow">{instrument}{!result.quote?' · RELATIVNÍ INDEX':''}</div><strong className={result.score!==null&&result.score<0?'negative':'positive'}>{fmt(result.score)}</strong><h2>{result.bias}</h2><p>{result.quote?'Rozdíl fundamentu obou měn.':'Měna vůči rovnocennému koši ostatních pěti měn.'} Rozsah −12 až +12.</p><small>Směr modelu, nikoli pravděpodobnost zisku. Plus neznamená souhlas všech faktorů.</small></section><section className="panel f-factors"><h2>Co tvoří skóre</h2>{result.parts.map(f=><div className="f-factor" key={f.id}><span>{f.label}<small>Váha {f.weight}</small></span><b className={f.value!==null&&f.value<0?'negative':'positive'}>{fmt(f.value)}</b></div>)}<small>{result.available}/4 pilíře s ověřenými zdroji · {data.methodVersion}</small></section></div>
 <div className="f-ranks">{currencies.map(c=>{const r=fundamentalScore(data,c,now);return <button key={c} onClick={()=>setInstrument(c)} className={instrument===c?'selected':''}><span>{c}</span><b className={r.score!==null&&r.score<0?'negative':'positive'}>{fmt(r.score)}</b><small>vlastní index</small></button>})}</div>
 <div className="f-tabs" role="tablist">{[['report','Report & scénáře'],['indicators','11 ukazatelů'],['calendar','Makro kalendář'],['method','Metodika & historie']].map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='report'&&<><div className="f-reports">{selected.map(c=>{const d=data.currencies[c];return <article className="panel f-report" key={c}><div className="eyebrow">{c} · {d.bank}</div><h2>Sazba {d.rate}</h2><small>Poslední rozhodnutí {date(d.decisionDate,false)}</small><ul>{d.facts.map((f,i)=><li key={i}>{f}</li>)}</ul>{source(d.source)}<h3>Scénář · interpretace modelu</h3><p>{d.scenario}</p><h3>Co může změnit výhled</h3><p>{d.risk}</p><details><summary>Vstupy a jejich zdůvodnění</summary>{coreFactors.map(f=><div className="f-evidence" key={f.id}><b>{f.label}: {fmt(d.factors[f.id].value)}</b><p>{d.factors[f.id].reason}</p>{source(d.factors[f.id].source)}</div>)}</details></article>})}</div><section className="panel f-report"><div className="eyebrow">POHLED INSTITUCÍ</div>{data.institutions.map((i,n)=><article key={n}><h2>{i.name} · {date(i.date,false)}</h2><p>{i.view}</p><p className="muted">{i.caveat}</p>{source(i.source)}</article>)}<p className="small-note">Publikovaný názor konkrétní instituce, nikoli konsensus všech bank. Nezvyšuje automaticky skóre.</p></section></>}
 {tab==='indicators'&&<section className="panel f-report"><h2>Ukazatele · {instrument}</h2><p className="muted">Pomlčka znamená chybějící ověřená data, nikoli neutrální signál. Dosavadní skóre stále používá čtyři pilíře; ostatní údaje jsou doplňkový kontext.</p>{(data.indicators||[]).map(i=><article className="f-indicator" key={i.id}><h3>{i.label}</h3><p>{i.description}</p><div className="f-reports">{(['trend','seasonality','retailPositions'].includes(i.id)?[instrument]:selected).map(c=>{const o=['trend','seasonality','retailPositions'].includes(i.id)?data.pairObservations?.[instrument]?.[i.id]:data.observations?.[c]?.[i.id];const stale=o?.checkedAt?now-Date.parse(o.checkedAt)>data.staleAfterHours*3600000:false;return <div key={c}><b>{c}</b><p>{o?.value??'— Neověřeno'}</p><small>{o?.period?'Období: '+o.period+' · ':''}{o?.checkedAt?(stale?'Zastaralé ověření: ':'Ověřeno: ')+date(o.checkedAt):'Konkrétní hodnoty dosud neověřeny'}</small><p>{o?.note??(i.id==='retailPositions'?'Pro tento pár či index zatím není ověřený vzorek retail pozic. Údaje jiné měny sem nepřenášíme.':'Zdroj konkrétního údaje dosud nebyl ověřen.')}</p>{o?.sourceUrl&&<a className="text-link" href={o.sourceUrl} target="_blank" rel="noreferrer">{o.value?'Zdroj údaje':'Zdroj ke sledování'} ↗</a>}</div>})}</div></article>)}</section>}
 {tab==='calendar'&&<section className="panel f-report"><h2>Nadcházející makro a zasedání</h2><p className="muted">Všechny sledované měny. Časy jsou v Praze. Blízkost události zvyšuje nejistotu, sama neurčuje směr.</p>{[...data.events].sort((a,b)=>a.at.localeCompare(b.at)).map(e=><article className="f-event" key={e.id}><div><span className="tag">{e.currency}</span><h3>{e.title}</h3><small>{date(e.at,e.timeKnown)}{!e.timeKnown?' · přesný čas neověřen':''}</small></div><div><p>{e.watch}</p><small>{Date.parse(e.at)<now?'Termín uplynul — výsledek ověřit':Date.parse(e.at)-now<86400000?'Blíží se do 24 hodin':'Plánovaná událost'} · {e.importance}</small><p>Konsensus: {e.consensus??'nedostupný'} · Výsledek: {e.actual??'dosud nepotvrzený'}</p>{source(e.source)}</div></article>)}</section>}
 {tab==='method'&&<section className="panel f-report"><h2>Otevřený výpočet, dohledatelné zdroje</h2><p>{data.coverageNote}</p><p>Každý vstup má −1, 0 nebo +1. Pár = vážený součet vstupů základní měny minus stejný součet kotovací měny. Vlastní index = měna minus průměr ostatních pěti. Není to burzovní cenový index.</p>{coreFactors.map(f=><p key={f.id}><b>{f.label} × {f.weight}.</b> {f.rule}</p>)}<p>Model nezohledňuje kompletně očekávání již zahrnutá v ceně. Zvýšení sazby může doprovázet oslabení měny. Po {data.staleAfterHours} hodinách bez ověření nebo při chybějícím vstupu se směrové skóre nezobrazí. Kontroly závisejí na běhu naplánované úlohy v Codexu; nejde o živý tržní feed.</p><h3>Změny reportu</h3>{data.changes.map((c,i)=><p key={i}><b>{date(c.at)} · {c.title}</b><br/>{c.body}</p>)}<h3>Historie skutečných pozorování</h3>{data.history.length<2?<p>První ověřený záznam je uložen. Historie začne růst s dalšími změnami vstupů; minulý vývoj nedoplňujeme odhadem.</p>:data.history.map((h,i)=><p key={i}>{date(h.at)} · {h.methodVersion} · {JSON.stringify(h.values[instrument.split('/')[0]])}</p>)}<h3>Zdroje</h3>{Object.entries(data.sources).map(([id,s])=><p key={id}>{source(id)}<br/><small>Ověřeno {date(s.checkedAt)}{s.publishedAt?' · Publikováno '+date(s.publishedAt,false):''}</small></p>)}</section>}
 </div>
}
