export const currencies=['EUR','USD','NZD','AUD','CAD','JPY'];
export const factors=['COT pozice','HDP','Sezónnost','Trend','Maloobchodní tržby','Retail pozice','Výrobní PMI','PMI služeb','Úrokové sazby','Inflace','Zaměstnanost'];
export const demo:Record<string,number[]>={EUR:[-3,2,0,0,-2,-1,-1,0,0,0,-1],USD:[0,0,0,0,0,0,0,0,0,0,0],NZD:[-1,-1,0,-1,0,0,-1,0,0,0,0],AUD:[1,0,1,0,0,-1,1,0,0,0,0],CAD:[0,1,0,0,-1,0,0,1,0,0,0],JPY:[1,0,0,1,0,0,0,0,1,0,0]};
export const pairs=currencies.flatMap((c,i)=>currencies.slice(i+1).map(d=>c+'/'+d));
export function scores(data:Record<string,number[]>,instrument:string){const [a,b]=instrument.split('/');return factors.map((_,i)=>b?data[a][i]-data[b][i]:data[a][i]-currencies.filter(c=>c!==a).reduce((s,c)=>s+data[c][i],0)/5)}
export const total=(arr:number[])=>Math.round(arr.reduce((s,n)=>s+n,0)*10)/10;
export const signed=(n:number)=>n>0?'+'+n:String(n);
export function parseTrades(input:string){const lines=input.trim().split(/\r?\n/);if(lines.length<2)throw new Error('CSV musí obsahovat hlavičku date,pair,r a alespoň jeden obchod.');const split=(s:string)=>s.split(s.includes(';')?';':',').map(x=>x.trim());const head=split(lines[0]);const d=head.indexOf('date'),p=head.indexOf('pair'),r=head.indexOf('r');if(Math.min(d,p,r)<0)throw new Error('Požadované sloupce: date,pair,r. Čísla zapisuj s desetinnou tečkou.');return lines.slice(1).filter(x=>x.trim()).map((line,i)=>{const a=split(line),n=Number(a[r]);if(!/^\d{4}-\d{2}-\d{2}$/.test(a[d]||'')||isNaN(Date.parse(a[d]))||!(pairs.includes(a[p])||pairs.includes(a[p]?.split('/').reverse().join('/')))||!a[r]||!Number.isFinite(n))throw new Error(`Zkontroluj řádek ${i+2}: datum YYYY-MM-DD, podporovaný pár a číselný výsledek R.`);return {date:a[d],pair:a[p],r:n}}).sort((a,b)=>a.date.localeCompare(b.date))}
export function stats(trades:{r:number}[]){let equity=0,peak=0,dd=0;const path=[0];for(const t of trades){equity+=t.r;peak=Math.max(peak,equity);dd=Math.max(dd,peak-equity);path.push(equity)}const wins=trades.filter(t=>t.r>0),loss=trades.filter(t=>t.r<0);const gross=wins.reduce((a,t)=>a+t.r,0),lost=-loss.reduce((a,t)=>a+t.r,0);return {count:trades.length,win:trades.length?wins.length/trades.length*100:0,net:equity,dd,pf:lost?gross/lost:null,path}}
