CREATE TABLE IF NOT EXISTS waitlist(
  email VARCHAR(254) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NULL,
  google_sub VARCHAR(64) NULL UNIQUE,
  source VARCHAR(16) NOT NULL,
  approved TINYINT(1) NOT NULL DEFAULT 0,
  created DATETIME NOT NULL,
  approved_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
